### ISSUE TITLE
Fix map bounds on user profile & event show pages

### ISSUE THREAD

**Issue by stephaniejue** [stephaniejue/VolunteerUP#141]
The map on user's profile page isn't loading correctly. The markers are off the page or high up in the left hand corner. It should be center and show all event markers. It doesn't need to show the users marker unless its within the bounds of the existing markers.

![screen shot 2017-01-29 at 11 47 55 am](https://cloud.githubusercontent.com/assets/20118615/22407678/fb369cfc-e61f-11e6-849b-c38820b6dbda.png)

**Comment by suzmas** [comment]
Also an issue on the event show page- 

![image](https://cloud.githubusercontent.com/assets/22352077/22613655/effb4118-ea2e-11e6-86fe-43c3009b50a1.png)
