### ISSUE TITLE
Users signing in with social media can't update account settings

### ISSUE THREAD

**Issue by stephaniejue** [stephaniejue/VolunteerUP#216]
Because users that sign in with social media are not provided a password, they can't update their account settings (which requires a password). Either remove the password confirmation on account settings or figure out a way to provide users their password on initial login.

**Comment by stephaniejue** [comment]
@suzmas which route did you take for this?

Also, this is showing up as largely untested in our coverage sheet. Do you think you could add some test for this? Or would it be too hard since its a devise controller?

![screen shot 2017-02-01 at 8 16 39 pm](https://cloud.githubusercontent.com/assets/20118615/22635315/6ce10762-ebe7-11e6-91a8-3f61baceaf73.png)

**Comment by suzmas** [comment]
This overrides the Devise update controller so that passwords are not necessary for updates other than email&password. I'll try to write a feature test for it, but it's Devise & OmniAuth so I'm not sure how that'll go.

**Comment by stephaniejue** [comment]
I'm going to update the form too so that that's clear
