### ISSUE TITLE
Past events

### ISSUE THREAD

**Issue by sslampa** [stephaniejue/VolunteerUP#221]
How are we going to deal with events that are finished? Obviously we shouldn't delete them, but are we just hiding them? Also, how will users be able to access those old events?

**Comment by suzmas** [comment]
Let's just hide them... Should be pretty easy to add something to user's page like a link to see "Event History" or something. Would look nice as a modal like the organizer volunteer list (IMO)!

**Comment by stephaniejue** [comment]
Agreed! Hide them, but have a tab for users to look at past events.

**Comment by sslampa** [comment]
Is there anything left for this?
