### ISSUE TITLE
Adding pictures to an event/organization

### ISSUE THREAD

**Issue by sslampa** [stephaniejue/VolunteerUP#222]
I was thinking some kind of carousel should be added to each individual's event/organization page.

**Comment by suzmas** [comment]
Still thinking about doing this? Carousel? As far as past events pages... does that mean we have to archive a copy of every events page. Foreva?

**Comment by sslampa** [comment]
Yea, I'm still thinking about doing this at some point. I need to change the db seed first so that it has past events (and change all the views so that they don't show old events). As far as archiving, I just assumed we would never delete an event unless an organizer did so.
