### ISSUE TITLE
Adjust event map to pagination display

### ISSUE THREAD

**Issue by suzmas** [stephaniejue/VolunteerUP#225]
Agreed or disagreed? Map locations should only be shown for the events currently displayed- when the pagination page changes, the map should update.

**Comment by sslampa** [comment]
I'm definitely not opposed to the idea, but I'm not entirely sure how we'd implement it. In its current form, the map can only be updated by a page reload that happens when "Search" is pressed.

**Comment by suzmas** [comment]
https://developers.google.com/maps/documentation/javascript/examples/place-search-pagination

Here's what I found so far. I'll take a look at the quode today.
