### ISSUE TITLE
Say Hello To Steph and Suz

### ISSUE THREAD

**Issue by suzmas** [stephaniejue/VolunteerUP#252]
You did not say hi to me. Please fix.

**Comment by suzmas** [comment]
Stephen said hi.

![image](https://cloud.githubusercontent.com/assets/22352077/22816777/c59db16e-ef18-11e6-9594-58aaabaea94b.png)

**Comment by stephaniejue** [comment]
Not done

**Comment by sslampa** [comment]
Said hello to both
