### ISSUE TITLE
AWS Region Issue

### ISSUE THREAD

**Issue by suzmas** [stephaniejue/VolunteerUP#253]
When trying to sign up w/ facebook:

![image](https://cloud.githubusercontent.com/assets/22352077/22817355/94d009c6-ef1b-11e6-99d4-e09e87aa03f4.png)

Google says: 
![image](https://cloud.githubusercontent.com/assets/22352077/22817372/b30b7c40-ef1b-11e6-9bff-8c9cc9bcd870.png)

I'm not sure who has our aws account but if you could check it out! Thanks

**Comment by stephaniejue** [comment]
@suzmas us-west-1
