### ISSUE TITLE
Social Media Pro Pic Edits

### ISSUE THREAD

**Issue by suzmas** [stephaniejue/VolunteerUP#265]
Hey guys, I'm not sure what happened here. I set this up about a week ago and it was working fine. Some changes were made, and now it doesn't work.  Someone also changed: VolunteerUP/spec/features/edit_profiles_spec.rb and commented out the test for updating a profile picture with no password. Not sure why- this doesn't work, and now it's not being caught since the test is commented out. 

Just wondering about which things were changed here exactly so I can try to get it back to passing.

**Comment by stephaniejue** [comment]
@suzmas my bad that was me. For some reason with the js: true it wasn't allowing me to attach an image in the test. I meant to check on it but forgot sorry! I'll look into it.

Is it only the test that isn't working or was there something else?

**Comment by sslampa** [comment]
As of right now, neither Suz or I can log in with Facebook. We get an S3 error
