### ISSUE TITLE
Create image upload spec separate from edit_user spec

### ISSUE THREAD

**Issue by stephaniejue** [stephaniejue/VolunteerUP#267]
The edit user spec requires chromedriver and js: true. Attaching an image doesn't work the way it does without that so we're going to move the tests into a different spec file and test image edits without js:true.

**Comment by sslampa** [comment]
I actually may have solved the tests in my most recent commit. So if you guys could check that before doing anything big.

**Comment by stephaniejue** [comment]
@sslampa looks good!
