### ISSUE TITLE
General Styling Things

### ISSUE THREAD

**Issue by suzmas** [stephaniejue/VolunteerUP#281]
![image](https://cloud.githubusercontent.com/assets/22352077/23243497/3c66aa6a-f934-11e6-9314-dba606f910c7.png)

**Comment by suzmas** [comment]
Sometimes font is very small and hard to read- even more so on mobile. An old person I demoed the site to mentioned this. :-D The cause tags for instance:

![image](https://cloud.githubusercontent.com/assets/22352077/23243173/057781ac-f932-11e6-8262-f5ab024b4a7a.png)


Thoughts?

**Comment by sslampa** [comment]
Yea I think especially for the more important things, we can make the fonts larger
