### ISSUE TITLE
Event Fbook Share Buttons in 'development' mode

### ISSUE THREAD

**Issue by mrobock** [stephaniejue/VolunteerUP#296]
Facebook Share button error on event's page:
App Not Setup: This app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permissions.

**Comment by stephaniejue** [comment]
@mrobock can you screen shot it for me... mine doesn't do that.

![screen shot 2017-02-26 at 9 53 25 am](https://cloud.githubusercontent.com/assets/20118615/23342127/82a6215e-fc09-11e6-8e22-d92b39519432.png)

**Comment by mrobock** [comment]
<img width="1175" alt="screen shot 2017-02-26 at 10 07 32 am" src="https://cloud.githubusercontent.com/assets/23323639/23342232/85209d0e-fc0b-11e6-85aa-32d952560dca.png">

**Comment by stephaniejue** [comment]
@mrobock thanks! it should work now. Can you check again for me?

**Comment by stephaniejue** [comment]
Fixed by #299

**Comment by mrobock** [comment]
[image: Inline image 1]
